### PR TITLE
add return value

### PR DESCRIPTION
**Pull request by DJMaster**

### CODE REVIEW

**Comment by LaurentGomila** [comment]
No need to do two commits, and worse, two PR, for such a small patch ;)

Please close one of your PRs and modify the other to have a single clean commit :+1:

**Comment by BlaXpirit** [comment]
@LaurentGomila I have a strong suspicion that this was done using GitHub's web interface (limited to editing one file, branch named `patch-x`), so @DJMaster  may not want to redo it in the command line.

**Comment by DJMaster** [comment]
Sorry for the double PR, but from the github web interface I can't do better...

**Comment by DJMaster** [comment]
Created new pull request #101.

**Pull request closed without merging**
